# PowerBI Cloud Connections Main Configuration
version: '1.0'

# Configuration file references
configurationFiles:
  servicePrincipals: servicePrincipals.yaml
  connectionTargets: connectionTargets.yaml
  
  # Connection group files
  connections:
    - development: connections/development.yaml

# Global settings
settings:
  vaultBaseUrl: https://endjintest.vault.azure.net/secrets
  defaultOwner: jessica.hill@endjin.com
  defaultTenantId: 0f621c67-98a0-4ed5-b5bd-31a35be41e29

# Note: You can add more connection group files by adding them to the connections list above.
# This allows for flexible organization of connections based on:
# - Environment (dev, test, prod)
# - Department or team
# - Purpose or project
# - Any other logical grouping
